apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-isilon-pvc
  namespace: isilon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: test-isilon-nfs
