apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocsfspvc
  namespace: vm-home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem