apiVersion: v1
kind: Pod
metadata:
  name: dynamic-fc-pmax-pod
  namespace: powermax
spec:
  containers:
  - name: task-pv-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: dy-fc-pmax
  volumes:
    - name: dy-fc-pmax
      persistentVolumeClaim:
        claimName: dynamic-fc-powermax-pvc
