apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-iscsi-powermax-pvc
  namespace: powermax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: test-powermax-iscsi
