apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-powermax-iscsi
  namespace: powermax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeName: static-pv-powermax-iscsi
  storageClassName: test-powermax-iscsi
