# Local storage operator is installed in a namespace openshift-local-storage
# oc create -f lso-operator.yaml will create namespace, Operator Group and Subscription
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  targetNamespaces:
  - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator-subscription
  namespace: openshift-local-storage
spec:
  channel: "4.6" 
  name: local-storage-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
