apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-powerstore-pvc
  namespace: powerstore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: powerstore-nfs
