apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-powerstore-pvc
  namespace: powerstore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: powerstore-xfs
