apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isilon-image-registry
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 110Gi
  storageClassName: isilon-nfs
