apiVersion: v1
kind: Namespace
metadata:
  name: isilon
---
apiVersion: v1
kind: Secret
metadata:
  name: isilon-creds
  namespace: isilon
type: Opaque
data:
  # specify base64 contents of unisphere
  username: <base64 contents of username>
  password: <base64 contents of password>
