---
# tasks file for bind
- name: identify number of '255' in {{ ansible_default_ipv4.netmask }}
  set_fact:
    striped_netmask: "{{ ansible_default_ipv4.netmask | regex_findall('(255)') |length }}" 

- debug:
    msg: custom netmask is {{ striped_netmask|int }}

- name: number of octets to remove
  set_fact:
    strip_last_octets: "{{ 4 - striped_netmask|int }}"

- debug:
    msg: last {{ strip_last_octets }} octet(s) in reverse order will be added in reverse zone file for {{ ansible_default_ipv4.network }}

- name: set reverse zone name prefix
  set_fact:
    arpa_name_prefix: "{{ ansible_default_ipv4.network.split('.')[:striped_netmask|int][::-1] }}"

- name: set reverse zone file name
  set_fact:
    arpa_name: "{{ arpa_name_prefix | join('.') }}.in-addr.arpa"

- debug:
    msg: reverse zone name is {{ arpa_name }}

- name: install dns 
  yum:
    name: bind
    state: latest

- name: generate dns config
  template:
    src: named.conf.j2
    dest: /etc/named.conf
  notify: "restart named"

- name: generate zone config file 
  template:
    src: zones.j2
    dest: /var/named/{{ cluster }}.zones

- name: generate forward zone file
  template:
    src: forward.dns.j2
    dest: /var/named/{{ ansible_domain }}
  notify: "restart named"

- name: generate reverse zone file
  template:
    src: reverse.dns.j2
    dest: /var/named/{{ arpa_name }}
  notify: "restart named"

- name: enable and start bind service
  systemd:
    name: named
    enabled: yes
    state: started

- name: modify dns server for bond0 interface
  nmcli:
    conn_name: bond0
    type: bond
    state: present
    dns4:
    - "{{ ansible_default_ipv4.address }}"
    dns4_search:
    - "{{ ansible_domain }}"
  notify: "reload NetworkManager"
