apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-unity-fc
  namespace: unity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  volumeName: static-pv-unity-fc
  storageClassName: test-unity-fc
