apiVersion: v1
kind: Pod
metadata:
  name: static-iscsi-unity-pod
  namespace: unity
spec:
  containers:
  - name: task-pv-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: st-iscsi-unity
  volumes:
    - name: st-iscsi-unity
      persistentVolumeClaim:
        claimName: static-iscsi-unity-pvc
