apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-iscsi-unity-pvc
  namespace: unity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  volumeName: static-pv-unity-iscsi
  storageClassName: test-unity-iscsi
