# PerformanceProfile for real time kernel
# Disabled SMT
# Hardware Used: PowerEdge XE2420 Servers
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
 name: nosmt-performanceprofile
spec:
 additionalKernelArgs:
  - nosmt # disabling SMT can reduce latency when used alongside the real time kernel
 cpu:
  # number of CPU cores will vary based on hardware configuration and whether SMT is enabled
  isolated: "1,3,5,7-47"
  reserved: "0,2,4,6"
 hugepages:
  defaultHugepagesSize: 1G
  pages:
  - size: "1G"
    count: 16
 realTimeKernel:
  enabled: true
 numa:
  topologyPolicy: "restricted"
  # topologyPolicy: "best-effort" # Can also use this policy, may change performance
 nodeSelector:
  node-role.kubernetes.io/worker-cnf: ""
