apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
 name: rt-performanceprofile
spec:
 additionalKernelArgs:
  - nosmt # disabling SMT can reduce latency when used alongside the real time kernel
 cpu:
  # number of CPU cores will vary based on hardware configuration and whether SMT is enabled
  isolated: "6-47"
  reserved: "0-5"
 hugepages:
  defaultHugepagesSize: 1G
  pages:
  - size: "1G"
    count: 16
 realTimeKernel:
  enabled: true
 nodeSelector:
  node-role.kubernetes.io/worker-cnf: ""
