apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: dpdk
  labels:
    machineconfiguration.openshift.io/role: dpdk
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [dpdk, worker],
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/dpdk: ""
